name: checkout
on:
  workflow_call:
jobs:
  source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/upload-artifact@v4
        with:
          name: source
          path: .
